"""create market instrument tables

Revision ID: 0ff190c777ce
Revises: 
Create Date: 2026-09-04 20:15:02.873255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff190c777ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('underlyings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('segment', sa.String(length=30), nullable=False),
    sa.Column('underlying_type', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_underlying_exchange_symbol')
    )
    op.create_index(op.f('ix_underlyings_exchange'), 'underlyings', ['exchange'], unique=False)
    op.create_index(op.f('ix_underlyings_segment'), 'underlyings', ['segment'], unique=False)
    op.create_index(op.f('ix_underlyings_symbol'), 'underlyings', ['symbol'], unique=False)
    op.create_table('option_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('trading_symbol', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['underlying_id'], ['underlyings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying_id', 'expiry_date', 'strike_price', 'option_type', name='uq_option_contract')
    )
    op.create_index(op.f('ix_option_contracts_exchange'), 'option_contracts', ['exchange'], unique=False)
    op.create_index(op.f('ix_option_contracts_expiry_date'), 'option_contracts', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_option_contracts_option_type'), 'option_contracts', ['option_type'], unique=False)
    op.create_index(op.f('ix_option_contracts_strike_price'), 'option_contracts', ['strike_price'], unique=False)
    op.create_index(op.f('ix_option_contracts_trading_symbol'), 'option_contracts', ['trading_symbol'], unique=True)
    op.create_index(op.f('ix_option_contracts_underlying_id'), 'option_contracts', ['underlying_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_contracts_underlying_id'), table_name='option_contracts')
    op.drop_index(op.f('ix_option_contracts_trading_symbol'), table_name='option_contracts')
    op.drop_index(op.f('ix_option_contracts_strike_price'), table_name='option_contracts')
    op.drop_index(op.f('ix_option_contracts_option_type'), table_name='option_contracts')
    op.drop_index(op.f('ix_option_contracts_expiry_date'), table_name='option_contracts')
    op.drop_index(op.f('ix_option_contracts_exchange'), table_name='option_contracts')
    op.drop_table('option_contracts')
    op.drop_index(op.f('ix_underlyings_symbol'), table_name='underlyings')
    op.drop_index(op.f('ix_underlyings_segment'), table_name='underlyings')
    op.drop_index(op.f('ix_underlyings_exchange'), table_name='underlyings')
    op.drop_table('underlyings')
    # ### end Alembic commands ###
