"""add market data and option chain snapshots

Revision ID: 30db62305d50
Revises: 0ff190c777ce
Create Date: 2026-09-04 20:21:08.168744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30db62305d50'
down_revision: Union[str, Sequence[str], None] = '0ff190c777ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['underlying_id'], ['underlyings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying_id', 'timeframe', 'candle_time', name='uq_market_candle')
    )
    op.create_index(op.f('ix_market_candles_candle_time'), 'market_candles', ['candle_time'], unique=False)
    op.create_index(op.f('ix_market_candles_timeframe'), 'market_candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_candles_underlying_id'), 'market_candles', ['underlying_id'], unique=False)
    op.create_table('option_chain_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_contract_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ask_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('oi_change', sa.Integer(), nullable=True),
    sa.Column('implied_volatility', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('delta', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('theta', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_contract_id'], ['option_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_contract_id', 'snapshot_time', name='uq_option_chain_snapshot')
    )
    op.create_index(op.f('ix_option_chain_snapshots_option_contract_id'), 'option_chain_snapshots', ['option_contract_id'], unique=False)
    op.create_index(op.f('ix_option_chain_snapshots_snapshot_time'), 'option_chain_snapshots', ['snapshot_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_chain_snapshots_snapshot_time'), table_name='option_chain_snapshots')
    op.drop_index(op.f('ix_option_chain_snapshots_option_contract_id'), table_name='option_chain_snapshots')
    op.drop_table('option_chain_snapshots')
    op.drop_index(op.f('ix_market_candles_underlying_id'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_timeframe'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_candle_time'), table_name='market_candles')
    op.drop_table('market_candles')
    # ### end Alembic commands ###
