"""add strategy signal and opportunity tables

Revision ID: 6b2a393767a5
Revises: 05748adc3893
Create Date: 2026-09-04 20:29:41.849591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2a393767a5'
down_revision: Union[str, Sequence[str], None] = '05748adc3893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_strategies_category'), 'strategies', ['category'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('underlying_id', sa.Integer(), nullable=True),
    sa.Column('market_type', sa.String(length=30), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['underlying_id'], ['underlyings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'underlying_id', 'market_type', 'timeframe', name='uq_strategy_config_scope')
    )
    op.create_index(op.f('ix_strategy_configs_market_type'), 'strategy_configs', ['market_type'], unique=False)
    op.create_index(op.f('ix_strategy_configs_strategy_id'), 'strategy_configs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_configs_underlying_id'), 'strategy_configs', ['underlying_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_contract_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('confluence_count', sa.Integer(), nullable=False),
    sa.Column('strategy_count', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_contract_id'], ['option_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_detected_at'), 'opportunities', ['detected_at'], unique=False)
    op.create_index(op.f('ix_opportunities_direction'), 'opportunities', ['direction'], unique=False)
    op.create_index(op.f('ix_opportunities_option_contract_id'), 'opportunities', ['option_contract_id'], unique=False)
    op.create_index(op.f('ix_opportunities_rank'), 'opportunities', ['rank'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('strategy_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('option_contract_id', sa.Integer(), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_contract_id'], ['option_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_signals_option_contract_id'), 'strategy_signals', ['option_contract_id'], unique=False)
    op.create_index(op.f('ix_strategy_signals_signal_time'), 'strategy_signals', ['signal_time'], unique=False)
    op.create_index(op.f('ix_strategy_signals_signal_type'), 'strategy_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_strategy_signals_strategy_id'), 'strategy_signals', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_signals_strategy_id'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_signal_type'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_signal_time'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_option_contract_id'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_rank'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_option_contract_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_direction'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_detected_at'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_strategy_configs_underlying_id'), table_name='strategy_configs')
    op.drop_index(op.f('ix_strategy_configs_strategy_id'), table_name='strategy_configs')
    op.drop_index(op.f('ix_strategy_configs_market_type'), table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_strategies_category'), table_name='strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###
