"""add trades entries exits and journal

Revision ID: bed718b395d9
Revises: 6b2a393767a5
Create Date: 2026-09-04 20:34:32.620262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed718b395d9'
down_revision: Union[str, Sequence[str], None] = '6b2a393767a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('option_contract_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('position_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('planned_entry', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('planned_stop_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('planned_target', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pnl_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['option_contract_id'], ['option_contracts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_direction'), 'trades', ['direction'], unique=False)
    op.create_index(op.f('ix_trades_opportunity_id'), 'trades', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_trades_option_contract_id'), 'trades', ['option_contract_id'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_trade_date'), 'trades', ['trade_date'], unique=False)
    op.create_table('trade_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_entries_entry_time'), 'trade_entries', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trade_entries_trade_id'), 'trade_entries', ['trade_id'], unique=False)
    op.create_table('trade_exits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_exits_exit_time'), 'trade_exits', ['exit_time'], unique=False)
    op.create_index(op.f('ix_trade_exits_trade_id'), 'trade_exits', ['trade_id'], unique=False)
    op.create_table('trade_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('setup_quality', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('market_condition', sa.String(length=100), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('what_went_well', sa.Text(), nullable=True),
    sa.Column('what_went_wrong', sa.Text(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('mistake', sa.Text(), nullable=True),
    sa.Column('followed_plan', sa.Boolean(), nullable=True),
    sa.Column('emotional_state', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_journal_trade_id'), 'trade_journal', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_journal_trade_id'), table_name='trade_journal')
    op.drop_table('trade_journal')
    op.drop_index(op.f('ix_trade_exits_trade_id'), table_name='trade_exits')
    op.drop_index(op.f('ix_trade_exits_exit_time'), table_name='trade_exits')
    op.drop_table('trade_exits')
    op.drop_index(op.f('ix_trade_entries_trade_id'), table_name='trade_entries')
    op.drop_index(op.f('ix_trade_entries_entry_time'), table_name='trade_entries')
    op.drop_table('trade_entries')
    op.drop_index(op.f('ix_trades_trade_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_option_contract_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_opportunity_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_direction'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
